import Header from "../components/Header/Header";
import type { NextPage } from "next";
import Head from "next/head";

import { Container } from "reactstrap";

import Buttons from "@/components/Buttons/Buttons";
import Image from "next/image";
import TextTop from "@/components/TextTop/TextTop";
import Languages from "@/components/Languages/Languages";
import Cards from "@/components/Cards/Cards";
import Footer from "@/components/Footer/Footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      
      <main>
        <Container className="py-5 text-center">
          <TextTop />
          <Image
            style={{ borderRadius: "50%", objectFit: "cover" }}
            src={"/teste2.jpeg"}
            alt=""
            width={250}
            height={250}
            className="mb-5"
          />
          <Buttons />

          <Languages/>

          <Cards/>

        </Container>
      </main>
          <Footer/>
    </>
  );
};

export default Home;
